version: "3"

services:

  elaster:
    build: .
    image: ${DOCKER_REPO}:${DOCKER_IMAGE_DEV_TAG:-latest-dev}
    ports:
      - "5000:5000"
    environment:
      ENV: DEV
      # comment these two environment varailbes according to your requirement if you need to start app as for an example or not
      EXAMPLE: ${EXAMPLE_APP}
      DATASET_PATH: ${DATASET_PATH}
    volumes:
      - ./elaster:/project/elaster
    depends_on:
      - elasticsearch
  

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    environment:
      http.host: "0.0.0.0"
      transport.host: "127.0.0.1"
